eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/


    
lucky-word:
  Irish,Rabbit's Foot,Serendipity sameer
  
  
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
