eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
    
lucky-word:
  Irish,Rabbit's Foot,Serendipity will change this as per my
  
  

